#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Auto-start Programs
picom --config /home/rtc/.config/picom/picom.conf &
feh --bg-scale ~/docs/wallpaper.jpg &
~/.config/polybar/launch.sh &

connected_monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

for monitor in $connected_monitors; do
    case $monitor in
        eDP-1)
            bspc monitor $monitor -d 6 7 8 9 0
            ;;
        HDMI-1|DP-2)
            bspc monitor $monitor -d 1 2 3 4 5
            ;;
    esac
done

bspc wm -O DP-2 eDP-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
